version: '3.9'
services:
  api:
    build: .
    container_name: vehicles_api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./data:/app/data
  consumer:
    build: .
    container_name: vehicles_consumer
    command: npm run start:consumer
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./data:/app/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
